In [13]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
def f(x):
    return -np.exp(-(x-0.7)**2)

In [14]:
x = np.plot(x,f(x))

AttributeError: module 'numpy' has no attribute 'plot'

In [11]:
from scipy import optimize
result = sp.optimize.minimize_scalar(f)
print(result)

     fun: -1.0
    nfev: 13
     nit: 9
 success: True
       x: 0.6999999997839409


In [15]:
def f(x):
    return (x) -2.0 * x * ( x + 2.0) ** 2

In [17]:
result = optimize.minimize_scalar(f,bounds= (-3,-1),method = "Bounded")
print(result)

     fun: -2.0590582725107853
 message: 'Solution found.'
    nfev: 10
  status: 0
 success: True
       x: -2.11507074401239


In [19]:
result = optimize.minimize_scalar(f)
print (result)

     fun: -inf
    nfev: 529
     nit: 35
 success: True
       x: 1.0737622077212198e+103


C:\Users\freakylemon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in double_scalars
  


In [20]:
#multidimensional minimization

In [26]:
def fn(x):
    n = len(x)
    v = 0.
    for i in range(0,n):
        v = v + (x[i]-i) * (x[i]-i)
    return v

In [27]:
bnds = ((0,5),(0,5),(0,5),(0,5))
x0 = (0,0,0,0)
res = optimize .minimize(fn,x0,bounds = bnds)

In [28]:
print(res)

      fun: 1.1868228142039012e-15
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 1.00000000e-08, -5.81385558e-09,  7.70587811e-08,  9.42290862e-09])
  message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 15
      nit: 2
   status: 0
  success: True
        x: array([0.        , 0.99999999, 2.00000003, 3.        ])


In [43]:
#constraints to impose value x
cons = ({'type':'ineq','fun':lambda x: x[0]-2*x[1]+2},
        {'type':'ineq','fun':lambda x: -x[1]-2*x[3]+6},
        {'type':'ineq','fun':lambda x: -x[2]-2*x[3]+2})

In [45]:
res = optimize.minimize(fn,x0,bounds = bnds, constraints = cons) #ineq:inequality

In [47]:
res.x

array([0.        , 1.        , 0.80011318, 0.59994341])

In [49]:
res.fun

7.200000016012211

In [51]:
res.success

True

In [53]:
import numpy as np
import matplotlib.pyplot as plt

def flowTimes(maturity, frequency):
    small = 1e-10
    numPaymentsMinusOne = int(maturity * frequency - small)
    firstPayment = maturity - numPaymentsMinusOne / frequency
    return np.linspace(firstPayment, maturity, numPaymentsMinusOne +1)

flowTimes(1.0,2)

array([0.5, 1. ])

In [55]:
print(flowTimes(3.1,2))

[0.1 0.6 1.1 1.6 2.1 2.6 3.1]


In [57]:
print(flowTimes(2.9,2))

[0.4 0.9 1.4 1.9 2.4 2.9]


In [59]:
print(flowTimes(10.0,2))

[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


#Bond

In [1]:
import pandas as pd
bondDf = pd.read_csv('./giltBondPrices.txt',sep = '\t')

In [12]:
bondDf

epic           description  coupon   maturity     bid     ask  change  \
0   TR13  Uk Gilt Treasury Stk    4.50  07-Mar-13  101.92  102.07   -0.01   
1   T813  Uk Gilt Treasury Stk    8.00  27-Sep-13  107.86  107.98   -0.03   
2   TR14  Uk Gilt Treasury Stk    2.25  07-Mar-14  102.90  103.05    0.01   
3   T514  Uk Gilt Treasury Stk    5.00  07-Sep-14  109.28  109.43    0.02   
4   TR15  Uk Gilt Treasury Stk    2.75  22-Jan-15  105.57  105.68    0.05   
5    T4T  Uk Gilt Treasury Stk    4.75  07-Sep-15  112.92  113.04    0.04   
6    TY8  Uk Gilt Treasury Stk    8.00  07-Dec-15  124.39  124.55    0.04   
7   TS16  Uk Gilt Treasury Stk    2.00  22-Jan-16  104.92  105.04    0.07   
8    T16  Uk Gilt Treasury Stk    4.00  07-Sep-16  113.44  113.55    0.08   
9   TR17  Uk Gilt Treasury Stk    8.75  25-Aug-17  138.48  138.66    0.14   
10   T18  Uk Gilt Treasury Stk    5.00  07-Mar-18  121.74  121.84    0.16   
11   T19  Uk Gilt Treasury Stk    4.50  07-Mar-19  121.28  121.41    0.23   
12  TR19  Uk Gilt Treasury Stk    3.75  07-Sep-19  116.50  117.13    0.26   
13  TS20  Uk Gilt Treasury Stk    4.75  07-Mar-20  124.24  124.36    0.28   
14  TR20  Uk Gilt Treasury Stk    3.75  07-Sep-20  117.25  117.50    0.32   
15  TR21  Uk Gilt Treasury Stk    8.00  07-Jun-21  152.25  153.61    0.42   
16  TY21  Uk Gilt Treasury Stk    3.75  07-Sep-21  117.62  117.77    0.38   
17  TR22  Uk Gilt Treasury Stk    4.00  07-Mar-22  119.92  120.12    0.41   
18  TR25  Uk Gilt Treasury Stk    5.00  07-Mar-25  131.89  132.19    0.52   
19  TR27  Uk Gilt Treasury Stk    4.25  07-Dec-27  123.78  124.33    0.58   
20  TR28  Uk Gilt Treasury Stk    6.00  07-Dec-28  148.21  148.26    0.68   
21  TR30  Uk Gilt Treasury Stk    4.75  07-Dec-30  130.96  131.14    0.55   
22  TR32  Uk Gilt Treasury Stk    4.25  07-Jun-32  122.93  123.08    0.54   
23   T34  Uk Gilt Treasury Stk    4.50  07-Sep-34  126.09  126.18    0.58   
24   T4Q  Uk Gilt Treasury Stk    4.25  07-Mar-36  121.46  121.71    0.53   
25  TR38  Uk Gilt Treasury Stk    4.75  07-Dec-38  130.70  130.80    0.55   
26   T39  Uk Gilt Treasury Stk    4.25  07-Sep-39  120.90  121.15    0.54   
27   T40  Uk Gilt Treasury Stk    4.25  07-Dec-40  120.55  120.93    0.53   
28   T42  Uk Gilt Treasury Stk    4.50  07-Dec-42  125.77  126.07    0.58   
29   T46  Uk Gilt Treasury Stk    4.25  07-Dec-46  120.93  121.37    0.56   
30   T49  Uk Gilt Treasury Stk    4.25  07-Dec-49  120.99  121.34    0.53   
31  TR4Q  Uk Gilt Treasury Stk    4.25  07-Dec-55  122.49  122.90    0.55   
32  TR60  Uk Gilt Treasury Stk    4.00  22-Jan-60  117.60  118.06    0.51   

    income yield  gross redemption yield      mid  
0           4.41                    0.22  101.995  
1           7.41                    0.23  107.920  
2           2.18                    0.22  102.975  
3           4.57                    0.23  109.355  
4           2.60                    0.33  105.625  
5           4.20                    0.35  112.980  
6           6.43                    0.34  124.470  
7           1.91                    0.49  104.980  
8           3.52                    0.56  113.495  
9           6.31                    0.77  138.570  
10          4.11                    0.91  121.790  
11          3.71                    1.07  121.345  
12          3.21                    1.22  116.815  
13          3.82                    1.32  124.300  
14          3.19                    1.43  117.375  
15          5.23                    1.50  152.930  
16          3.19                    1.62  117.695  
17          3.33                    1.70  120.020  
18          3.79                    2.07  132.040  
19          3.43                    2.36  124.055  
20          4.05                    2.39  148.235  
21          3.62                    2.60  131.050  
22          3.46                    2.73  123.005  
23          3.57                    2.89  126.135  
24          3.50                    2.97  121.585  
25          3.63                 

# # 

In [3]:
bondDf['mid'] = 0.5 * (bondDf['bid'] + bondDf['ask'])

In [4]:
bondDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 10 columns):
epic                      33 non-null object
description               33 non-null object
coupon                    33 non-null float64
maturity                  33 non-null object
bid                       33 non-null float64
ask                       33 non-null float64
change                    33 non-null float64
income yield              33 non-null float64
gross redemption yield    33 non-null float64
mid                       33 non-null float64
dtypes: float64(7), object(3)
memory usage: 2.7+ KB


In [18]:
import pandas as pd
dowJones30Df = pd.read_pickle('.\DowJonesPricesFromYahoo.pkl')
dowJones30Df.dropna(inplace = True) 
#这里的inplace意味着，修改原数据，把里面na的数据全部都丢掉，然后返回。
#如果不用inplace，意味着Df并没有发生改变

In [19]:
dowJones30Df

AAPL        AXP          BA         CAT       CSCO  \
Date                                                                   
2008-03-19   17.400475  36.908495   61.077398   59.969324  21.842601   
2008-03-20   17.883556  40.406014   62.199996   60.042524  22.110390   
2008-03-24   18.723591  41.662660   63.439005   61.840057  22.886976   
2008-03-25   18.918164  41.750537   63.114701   62.336210  22.985165   
2008-03-26   19.465665  39.861175   63.447322   62.921833  22.119317   
2008-03-27   18.820201  39.395426   61.717695   62.653421  21.583740   
2008-03-28   19.190571  37.919086   61.094032   62.702221  21.494477   
2008-03-31   19.256324  38.419987   61.842429   63.678261  21.503403   
2008-04-01   20.065493  41.381453   63.098066   65.052848  22.297841   
2008-04-02   19.791744  40.994794   63.904671   63.857202  22.279988   
2008-04-03   20.344607  41.021156   63.314271   62.685956  21.628371   
2008-04-04   20.541868  40.520255   62.906813   63.304115  21.771191   
2008-04-07   20.918944  40.906915   62.349676   62.832362  21.369509   
2008-04-08   20.509667  40.836614   62.382932   63.108903  21.387361   
2008-04-09   20.321801  39.769164   65.359885   61.945798  21.003532   
2008-04-10   20.739127  39.751520   65.218523   61.579781  21.458773   
2008-04-11   19.744778  38.278259   63.912989   60.839623  20.869637   
2008-04-14   19.830660  37.687193   64.212347   61.441510  20.807153   
2008-04-15   19.911171  38.066535   62.948387   61.774986  20.628628   
2008-04-16   20.625064  38.595849   63.754992   64.272013  21.271320   
2008-04-17   20.731077  39.433930   63.954569   64.214817  21.324877   
2008-04-18   21.610021  40.166147   65.409782   69.681127  21.878307   
2008-04-21   22.565462  40.316121   65.767343   68.087811  22.217505   
2008-04-22   21.497300  38.789932   65.326622   67.009257  22.244284   
2008-04-23   21.858277  39.151630   68.261995   66.747790  22.708451   
2008-04-24   22.670133  39.857382   69.018710   66.854009  23.235102   
2008-04-25   22.776137  42.142256   70.548760   67.205356  22.851271   
2008-04-28   23.112952  42.248118   70.665183   67.842683  22.628114   
2008-04-29   23.490029  42.353980   71.122532   66.600714  22.770935   
2008-04-30   23.342423  42.362804   70.565394   66.903032  22.886976   
...                ...        ...         ...         ...        ...   
2014-11-18  114.537650  89.677901  129.029956   99.459803  26.017188   
2014-11-19  113.744106  89.598696  129.968101   98.738517  26.007407   
2014-11-20  115.370864  89.717504  130.056975   99.508535  26.222586   
2014-11-21  115.529576  89.489791  131.123503  103.758288  26.291052   
2014-11-24  117.672131  90.133319  132.930675  103.280680  26.437767   
2014-11-25  116.650449  90.489734  133.128177  103.553599  26.682289   
2014-11-26  118.039146  90.539232  133.098552  103.114980  26.829002   
2014-11-28  117.969712  91.499573  132.683794   98.056213  27.034400   
2014-12-01  114.140878  91.222362  130.738369   96.496672  26.985496   
2014-12-02  113.704428  92.073798  130.629741   96.993778  27.210457   
2014-12-03  114.993935  90.341227  130.323611   97.646835  27.337609   
2014-12-04  114.557485  90.915452  129.681726   97.149729  27.161553   
2014-12-05  114.071444  91.727285  130.560622   96.282234  26.897468   
2014-12-08  111.492439  92.628218  128.654692   92.841495  26.633383   
2014-12-09  113.198552  92.430213  128.042432   93.036435  26.819221   
2014-12-10  111.046068  91.826288  123.085054   90.667880  26.281272   
2014-12-11  110.718738  92.202501  121.830901   90.346230  26.398642   
2014-12-12  108.843999  90.093716  119.263332   88.211605  26.271491   
2014-12-15  107.356111  89.143278  120.556994   87.480569  26.095435   
2014-12-16  105.888058  87.361201  122.699920   87.080933  26.007407   
2014-12-17  108.526583  89.539296  123.499813   87.480569  26.222586   
2014-12-18  111.740420  92.242103  124.102203   89.371516  27.044181   
2014-12-19  110.877442  91.974795  124.655222   89.391007 

In [21]:
names = dowJones30Df.columns

In [22]:
names

Index(['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'CVX', 'DD', 'DIS', 'GE', 'GS',
       'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 'MRK', 'MSFT',
       'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'UTX', 'V', 'VZ', 'WMT', 'XOM'],
      dtype='object')

In [24]:
returns = dowJones30Df.pct_change(periods = 1) 
#period = 1意味着第一行不用算，那是标签行
returns.dropna(inplace = True)
returns.head()

AAPL       AXP        BA       CAT      CSCO       CVX  \
Date                                                                     
2008-03-20  0.027763  0.094762  0.018380  0.001221  0.012260  0.016119   
2008-03-24  0.046972  0.031100  0.019920  0.029938  0.035123  0.009614   
2008-03-25  0.010392  0.002109 -0.005112  0.008023  0.004290  0.006309   
2008-03-26  0.028940 -0.045254  0.005270  0.009395 -0.037670  0.004968   
2008-03-27 -0.033159 -0.011684 -0.027261 -0.004266 -0.024213 -0.006591   

                  DD       DIS        GE        GS    ...          NKE  \
Date                                                  ...                
2008-03-20 -0.000440  0.021127  0.053386  0.078924    ...     0.087983   
2008-03-24  0.026623  0.004389 -0.002401 -0.004175    ...     0.026907   
2008-03-25  0.013716  0.001248 -0.003476  0.004193    ...    -0.010278   
2008-03-26 -0.009937 -0.009975 -0.003756 -0.023103    ...    -0.030715   
2008-03-27 -0.009182 -0.011965 -0.008080 -0.041828    ...    -0.004376   

                 PFE        PG       TRV       UNH       UTX         V  \
Date                                                                     
2008-03-20 -0.000970  0.023006  0.029735 -0.006470  0.003636  0.138938   
2008-03-24  0.000971  0.008649 -0.002093  0.011042  0.019272 -0.071795   
2008-03-25  0.008248 -0.006145  0.001468 -0.012041 -0.002559  0.058932   
2008-03-26 -0.004331  0.001438 -0.004397 -0.033447 -0.007839  0.011225   
2008-03-27 -0.006283 -0.003303 -0.001893 -0.002933 -0.002873 -0.016416   

                  VZ       WMT       XOM  
Date                                      
2008-03-20  0.028181  0.048247  0.006751  
2008-03-24  0.023533  0.007515  0.011176  
2008-03-25 -0.001894 -0.010815 -0.008726  
2008-03-26 -0.020596 -0.002827  0.012441  
2008-03-27 -0.004981 -0.010019 -0.000696  

[5 rows x 30 columns]

In [ ]:
# mean variance asset

In [32]:
assetList = ['AAPL','CSCO']
numAssets = len(assetList)

In [34]:
newReturns = returns[assetList]

In [35]:
newReturns

AAPL      CSCO
Date                          
2008-03-20  0.027763  0.012260
2008-03-24  0.046972  0.035123
2008-03-25  0.010392  0.004290
2008-03-26  0.028940 -0.037670
2008-03-27 -0.033159 -0.024213
2008-03-28  0.019679 -0.004136
2008-03-31  0.003426  0.000415
2008-04-01  0.042021  0.036945
2008-04-02 -0.013643 -0.000801
2008-04-03  0.027934 -0.029247
2008-04-04  0.009696  0.006603
2008-04-07  0.018356 -0.018450
2008-04-08 -0.019565  0.000835
2008-04-09 -0.009160 -0.017947
2008-04-10  0.020536  0.021674
2008-04-11 -0.047946 -0.027454
2008-04-14  0.004350 -0.002994
2008-04-15  0.004060 -0.008580
2008-04-16  0.035854  0.031155
2008-04-17  0.005140  0.002518
2008-04-18  0.042397  0.025952
2008-04-21  0.044213  0.015504
2008-04-22 -0.047336  0.001205
2008-04-23  0.016792  0.020867
2008-04-24  0.037142  0.023192
2008-04-25  0.004676 -0.016519
2008-04-28  0.014788 -0.009766
2008-04-29  0.016315  0.006312
2008-04-30 -0.006284  0.005096
2008-05-01  0.034780  0.040172
...              ...       ...
2014-11-18  0.012984  0.004911
2014-11-19 -0.006928 -0.000376
2014-11-20  0.014302  0.008274
2014-11-21  0.001376  0.002611
2014-11-24  0.018546  0.005580
2014-11-25 -0.008682  0.009249
2014-11-26  0.011905  0.005499
2014-11-28 -0.000588  0.007656
2014-12-01 -0.032456 -0.001809
2014-12-02 -0.003824  0.008336
2014-12-03  0.011341  0.004673
2014-12-04 -0.003795 -0.006440
2014-12-05 -0.004243 -0.009723
2014-12-08 -0.022609 -0.009818
2014-12-09  0.015302  0.006978
2014-12-10 -0.019015 -0.020058
2014-12-11 -0.002948  0.004466
2014-12-12 -0.016932 -0.004817
2014-12-15 -0.013670 -0.006701
2014-12-16 -0.013675 -0.003373
2014-12-17  0.024918  0.008274
2014-12-18  0.029613  0.031332
2014-12-19 -0.007723  0.004340
2014-12-22  0.010378  0.016204
2014-12-23 -0.003542  0.001063
2014-12-24 -0.004709  0.001770
2014-12-26  0.017677  0.001767
2014-12-29 -0.000702  0.003880
2014-12-30 -0.012203 -0.003514
2014-12-31 -0.019019 -0.019041

[1709 rows x 2 columns]

In [37]:
assetReturns = newReturns.mean()
assetCovariance = newReturns.cov()

In [39]:
assetCovariance

AAPL      CSCO
AAPL  0.000440  0.000218
CSCO  0.000218  0.000417

In [41]:
assetReturns

AAPL    0.001298
CSCO    0.000338
dtype: float64